=  TGPL Exercise Solutions with a test-first approach.
:toc: preamble
:toc-title:
:toclevels: 1
// Refs:
:url-base: https://github.com/fenegroni/TGPL-exercise-solutions
:url-workflows: {url-base}/workflows
:badge-chapter4: image:{url-workflows}/Chapter 4/badge.svg?branch=main
:badge-chapter5: image:{url-workflows}/Chapter 5/badge.svg?branch=main
:badge-chapter6: image:{url-workflows}/Chapter 6/badge.svg?branch=main
:badge-chapter7: image:{url-workflows}/Chapter 7/badge.svg?branch=main

image:https://img.shields.io/github/license/fenegroni/TGPL-exercise-solutions?style=flat-square[]
image:https://img.shields.io/tokei/lines/github/fenegroni/TGPL-exercise-solutions?style=flat-square[]
{badge-chapter4}[link={url-base}/tree/master/chapter4]
{badge-chapter5}[link={url-base}/tree/master/chapter5]
{badge-chapter6}[link={url-base}/tree/master/chapter6]
{badge-chapter7}[link={url-base}/tree/master/chapter7]

Solutions to the exercises in the book
_The Go Programming Language_
using TAD: _Test Aided Development_.

Copyright (C) 2021, 2022  Filippo Erik Negroni

This program is free software:
you can redistribute it and/or modify it
under the terms of the GNU General Public License
as published by the Free Software Foundation,
either version 3 of the License,
or (at your option) any later version.

For a copy of the GNU General Public License
see <https://www.gnu.org/licenses/>.

== Test first approach

The development process begins with a first test
capturing a valuable assumption of the solution.

Strive to make this first test cheap and quick to write and run, but not useless.

Don't worry about whether it is a behaviour, interface, system, integration or unit test.
The only attribute that matters is the Return On Investment:
a measure of how much feedback the test generates per unit of time spent writing and running it.

Write enough implementation of the solution to validate if the test is valuable:
green bars (test pass rate) mean nothing.

If the test fails, evaluate if passing the test is still valuable.
If it is, continue the effort of writing enough of the solution until the next assumption.
If the test isn't valuable anymore, throw away the test and write a better one.

If the test passes, evaluate if a failing test would have been more valuable.
If it would have been so, continue writing enough of the solution to fail the test.

== Solutions

{badge-chapter4}[link={url-base}/tree/master/chapter4]

{badge-chapter5}[link={url-base}/tree/master/chapter5]

{badge-chapter6}[link={url-base}/tree/master/chapter6]

{badge-chapter7}[link={url-base}/tree/master/chapter7]
