=  _TGPL_ Exercise Solutions
// Refs:
:url-base: https://github.com/fenegroni/TGPL-exercise-solutions
:url-workflows: {url-base}/workflows
:url-actions: {url-base}/actions
:badge-exercise4-9: image:{url-workflows}/Exercise 4.9/badge.svg?branch=main
:badge-exercise5-1: image:{url-workflows}/Exercise 5.1/badge.svg?branch=main
:badge-exercise5-2: image:{url-workflows}/Exercise 5.2/badge.svg?branch=main
:badge-exercise5-3: image:{url-workflows}/Exercise 5.3/badge.svg?branch=main
:badge-exercise5-4: image:{url-workflows}/Exercise 5.4/badge.svg?branch=main
:badge-exercise5-5: image:{url-workflows}/Exercise 5.5/badge.svg?branch=main
:badge-exercise5-6: image:{url-workflows}/Exercise 5.6/badge.svg?branch=main
:badge-exercise5-7: image:{url-workflows}/Exercise 5.7/badge.svg?branch=main
:badge-exercise5-8: image:{url-workflows}/Exercise 5.8/badge.svg?branch=main
:badge-exercise5-9: image:{url-workflows}/Exercise 5.9/badge.svg?branch=main
:badge-exercise5-10: image:{url-workflows}/Exercise 5.10/badge.svg?branch=main
:badge-exercise5-11: image:{url-workflows}/Exercise 5.11/badge.svg?branch=main
:badge-exercise5-12: image:{url-workflows}/Exercise 5.12/badge.svg?branch=main
:badge-exercise5-13: image:{url-workflows}/Exercise 5.13/badge.svg?branch=main
:badge-exercise5-14: image:{url-workflows}/Exercise 5.14/badge.svg?branch=main
:badge-exercise5-15: image:{url-workflows}/Exercise 5.15/badge.svg?branch=main
:badge-exercise5-16: image:{url-workflows}/Exercise 5.16/badge.svg?branch=main
:badge-exercise5-17: image:{url-workflows}/Exercise 5.17/badge.svg?branch=main
:badge-exercise5-18: image:{url-workflows}/Exercise 5.18/badge.svg?branch=main
:badge-exercise5-19: image:{url-workflows}/Exercise 5.19/badge.svg?branch=main
:badge-chapter6: image:{url-workflows}/Chapter 6/badge.svg?branch=main
:badge-chapter7: image:{url-workflows}/Chapter 7/badge.svg?branch=main

image:https://img.shields.io/github/license/fenegroni/TGPL-exercise-solutions?style=flat-square[]
image:https://img.shields.io/tokei/lines/github/fenegroni/TGPL-exercise-solutions?style=flat-square[]

Solutions to the exercises in the book
_The Go Programming Language_.

Copyright (C) 2021, 2022  Filippo Erik Negroni

This program is free software:
you can redistribute it and/or modify it
under the terms of the GNU General Public License
as published by the Free Software Foundation,
either version 3 of the License,
or (at your option) any later version.

For a copy of the GNU General Public License
see <https://www.gnu.org/licenses/>.

== Chapter 4 - _Composite Types_

{badge-exercise4-9}[link={url-base}/tree/master/ch4ex9]

== Chapter 5 - _Functions_

{badge-exercise5-1}[link={url-base}/tree/master/ch5ex1]
{badge-exercise5-2}[link={url-base}/tree/master/ch5ex2]
{badge-exercise5-3}[link={url-base}/tree/master/ch5ex3]
{badge-exercise5-4}[link={url-base}/tree/master/ch5ex4]
{badge-exercise5-5}[link={url-base}/tree/master/ch5ex5]
{badge-exercise5-6}[link={url-base}/tree/master/ch5ex6]
{badge-exercise5-7}[link={url-base}/tree/master/ch5ex7]
{badge-exercise5-8}[link={url-base}/tree/master/ch5ex8]
{badge-exercise5-9}[link={url-base}/tree/master/ch5ex9]
{badge-exercise5-10}[link={url-base}/tree/master/ch5ex10]
{badge-exercise5-11}[link={url-base}/tree/master/ch5ex11]
{badge-exercise5-12}[link={url-base}/tree/master/ch5ex12]
{badge-exercise5-13}[link={url-base}/tree/master/ch5ex13]
{badge-exercise5-14}[link={url-base}/tree/master/ch5ex14]
{badge-exercise5-15}[link={url-base}/tree/master/ch5ex15]
{badge-exercise5-16}[link={url-base}/tree/master/ch5ex16]
{badge-exercise5-17}[link={url-base}/tree/master/ch5ex17]
{badge-exercise5-18}[link={url-base}/tree/master/ch5ex18]
{badge-exercise5-19}[link={url-base}/tree/master/ch5ex19]

== Chapter 6 - _Methods_

{badge-chapter6}[link={url-base}/tree/master/chapter6]

== Chapter 7 - _Interfaces_

{badge-chapter7}[link={url-base}/tree/master/chapter7]
