=  TGPL Exercise Solutions
:toc: preamble
:toc-title:
:toclevels: 1
// Refs:
:url-base: https://github.com/fenegroni/TGPL-exercise-solutions
:url-workflows: {url-base}/workflows
:url-actions: {url-base}/actions
:badge-all_chapters: image:{url-workflows}/All chapters/badge.svg?branch=main[link={url-actions}]
:badge-chapter4: image:{url-workflows}/Chapter 4/badge.svg?branch=main[link={url-actions}]
:badge-exercise4-9: image:{url-workflows}/Exercise 4.9/badge.svg?branch=main[link={url-actions}]
:badge-chapter5: image:{url-workflows}/Chapter 5/badge.svg?branch=main[link={url-actions}]
:badge-exercise5-1: image:{url-workflows}/Exercise 5.1/badge.svg?branch=main[link={url-actions}]
:badge-exercise5-2: image:{url-workflows}/Exercise 5.2/badge.svg?branch=main[link={url-actions}]
:badge-exercise5-3: image:{url-workflows}/Exercise 5.3/badge.svg?branch=main[link={url-actions}]
:badge-exercise5-4: image:{url-workflows}/Exercise 5.4/badge.svg?branch=main[link={url-actions}]
:badge-exercise5-5: image:{url-workflows}/Exercise 5.5/badge.svg?branch=main[link={url-actions}]

{badge-all_chapters}

Solutions to the exercises in the book
_The Go Programming Language_
using TDD.

Copyright (C) 2021  Filippo Erik Negroni

This program is free software:
you can redistribute it and/or modify it
under the terms of the GNU General Public License
as published by the Free Software Foundation,
either version 3 of the License,
or (at your option) any later version.

For a copy of the GNU General Public License
see <https://www.gnu.org/licenses/>.

== Rules of TDD
. Write no more of a unit test than sufficient to fail
(compilation failures are failures).
. Write no more production code than necessary
to pass the one failing unit test.

== TDD in Go

TDD in Go is pretty straightforward.
It's a pity though that even the official book
_The Go Programming Language_
does not cover testing until chapter 11.
It contains sound advise
on how to write tests
and shows off Go's simple yet powerful approach.

In this repository
you will find solutions to the exercises in the book,
developed using TDD.
Each exercise has its own `README.adoc`
describing the TDD approach taken.

== Solutions

* {url-base}/tree/master/chapter4[`Chapter 4`] {badge-chapter4} +
Composite Types
** {url-base}/tree/master/chapter4/exercise4.9[Exercise 4.9] {badge-exercise4-9} +
Write a program `wordfreq`
to report the frequency of each word in an input text file.
Call `input.Split(bufio.ScanWords)` before the first call to `Scan`
to break the input into words instead of lines.
* {url-base}/tree/master/chapter5[`Chapter 5`] {badge-chapter5} +
Functions
** {url-base}/tree/master/chapter5/exercise5.1[Exercise 5.1] {badge-exercise5-1} +
Change the `findlinks` program to traverse the `n.FirstChild` linked list
using recursive calls to `Visit` instead of a loop.
** {url-base}/tree/master/chapter5/exercise5.2[Exercise 5.2] {badge-exercise5-2} +
Write a function to populate a mapping from element names - `p`, `div`, `span` and so on -
to the number of elements with that name in an HTML document tree
** {url-base}/tree/master/chapter5/exercise5.3[Exercise 5.3] {badge-exercise5-3} +
Write a function that to print the contents of all text nodes in an HTML document tree.
Do not descend into <script> or <style> elements,
since their content are not visible in a web browser.
** {url-base}/tree/master/chapter5/exercise5.4[Exercise 5.4] {badge-exercise5-4} +
Extend the `Visit` function so that
it extracts other kinds of links from the document,
such as images, scripts, and style sheets.
** {url-base}/tree/master/chapter5/exercise5.5[Exercise 5.5] {badge-exercise5-5} +
Implement `countWordAndImages`.
