=  _TGPL_ Exercise Solutions
:toc: preamble
:toc-title:
:toclevels: 1
// Refs:
:url-base: https://github.com/fenegroni/TGPL-exercise-solutions
:url-workflows: {url-base}/workflows
:badge-chapter4: image:{url-workflows}/Chapter 4/badge.svg?branch=main
:badge-chapter5: image:{url-workflows}/Chapter 5/badge.svg?branch=main
:badge-chapter6: image:{url-workflows}/Chapter 6/badge.svg?branch=main
:badge-chapter7: image:{url-workflows}/Chapter 7/badge.svg?branch=main

image:https://img.shields.io/github/license/fenegroni/TGPL-exercise-solutions?style=flat-square[]
image:https://img.shields.io/tokei/lines/github/fenegroni/TGPL-exercise-solutions?style=flat-square[]
{badge-chapter4}[link={url-base}/tree/master/chapter4]
{badge-chapter5}[link={url-base}/tree/master/chapter5]
{badge-chapter6}[link={url-base}/tree/master/chapter6]
{badge-chapter7}[link={url-base}/tree/master/chapter7]

Solutions to the exercises in the book
_The Go Programming Language_.

Copyright (C) 2021, 2022  Filippo Erik Negroni

This program is free software:
you can redistribute it and/or modify it
under the terms of the GNU General Public License
as published by the Free Software Foundation,
either version 3 of the License,
or (at your option) any later version.

For a copy of the GNU General Public License
see <https://www.gnu.org/licenses/>.

== Solutions

{badge-chapter4}[link={url-base}/tree/master/chapter4]

{badge-chapter5}[link={url-base}/tree/master/chapter5]

{badge-chapter6}[link={url-base}/tree/master/chapter6]

{badge-chapter7}[link={url-base}/tree/master/chapter7]
