=  _TGPL_ Exercise Solutions
// Refs:
:url-base: https://github.com/fenegroni/TGPL-exercise-solutions
:url-workflows: {url-base}/workflows
:url-actions: {url-base}/actions
:url-link-base: {url-base}/tree/main
:url-badge-main: badge.svg?branch=main

image:https://img.shields.io/github/license/fenegroni/TGPL-exercise-solutions?style=flat[]
image:https://img.shields.io/tokei/lines/github/fenegroni/TGPL-exercise-solutions?style=flat[]

Solutions to the exercises in the book
_The Go Programming Language_.

Copyright (C) 2021, 2022 Filippo Erik Negroni

This program is free software:
you can redistribute it and/or modify it
under the terms of the GNU General Public License
as published by the Free Software Foundation,
either version 3 of the License,
or (at your option) any later version.

For a copy of the GNU General Public License
see <https://www.gnu.org/licenses/>.

== Chapter 4 - _Composite Types_

image:{url-workflows}/Exercise 4.9/{url-badge-main}[link={url-link-base}/ch4ex9]

== Chapter 5 - _Functions_

image:{url-workflows}/Exercise 5.1/{url-badge-main}[link={url-link-base}/ch5ex1]
image:{url-workflows}/Exercise 5.2/{url-badge-main}[link={url-link-base}/ch5ex2]
image:{url-workflows}/Exercise 5.3/{url-badge-main}[link={url-link-base}/ch5ex3]
image:{url-workflows}/Exercise 5.4/{url-badge-main}[link={url-link-base}/ch5ex4]
image:{url-workflows}/Exercise 5.5/{url-badge-main}[link={url-link-base}/ch5ex5]
image:{url-workflows}/Exercise 5.6/{url-badge-main}[link={url-link-base}/ch5ex6]
image:{url-workflows}/Exercise 5.7/{url-badge-main}[link={url-link-base}/ch5ex7]
image:{url-workflows}/Exercise 5.8/{url-badge-main}[link={url-link-base}/ch5ex8]
image:{url-workflows}/Exercise 5.9/{url-badge-main}[link={url-link-base}/ch5ex9]
image:{url-workflows}/Exercise 5.10/{url-badge-main}[link={url-link-base}/ch5ex10]
image:{url-workflows}/Exercise 5.11/{url-badge-main}[link={url-link-base}/ch5ex11]
image:{url-workflows}/Exercise 5.12/{url-badge-main}[link={url-link-base}/ch5ex12]
image:{url-workflows}/Exercise 5.13/{url-badge-main}[link={url-link-base}/ch5ex13]
image:{url-workflows}/Exercise 5.14/{url-badge-main}[link={url-link-base}/ch5ex14]
image:{url-workflows}/Exercise 5.15/{url-badge-main}[link={url-link-base}/ch5ex15]
image:{url-workflows}/Exercise 5.16/{url-badge-main}[link={url-link-base}/ch5ex16]
image:{url-workflows}/Exercise 5.17/{url-badge-main}[link={url-link-base}/ch5ex17]
image:{url-workflows}/Exercise 5.18/{url-badge-main}[link={url-link-base}/ch5ex18]
image:{url-workflows}/Exercise 5.19/{url-badge-main}[link={url-link-base}/ch5ex19]

== Chapter 6 - _Methods_

image:{url-workflows}/Exercise 6.1/{url-badge-main}[link={url-link-base}/ch6ex1]
image:{url-workflows}/Exercise 6.2/{url-badge-main}[link={url-link-base}/ch6ex2]
image:{url-workflows}/Exercise 6.3/{url-badge-main}[link={url-link-base}/ch6ex3]
image:{url-workflows}/Exercise 6.4/{url-badge-main}[link={url-link-base}/ch6ex4]
image:{url-workflows}/Exercise 6.5/{url-badge-main}[link={url-link-base}/ch6ex5]

== Chapter 7 - _Interfaces_

image:{url-workflows}/Exercise 7.1/{url-badge-main}[link={url-link-base}/ch7ex1]
image:{url-workflows}/Exercise 7.2/{url-badge-main}[link={url-link-base}/ch7ex2]
image:{url-workflows}/Exercise 7.3/{url-badge-main}[link={url-link-base}/ch7ex3]
image:{url-workflows}/Exercise 7.4/{url-badge-main}[link={url-link-base}/ch7ex4]
image:{url-workflows}/Exercise 7.5/{url-badge-main}[link={url-link-base}/ch7ex5]
image:{url-workflows}/Exercise 7.6/{url-badge-main}[link={url-link-base}/ch7ex6]
image:{url-workflows}/Exercise 7.7/{url-badge-main}[link={url-link-base}/ch7ex7]
image:{url-workflows}/Exercise 7.8/{url-badge-main}[link={url-link-base}/ch7ex8]
image:{url-workflows}/Exercise 7.9/{url-badge-main}[link={url-link-base}/ch7ex9]
image:{url-workflows}/Exercise 7.10/{url-badge-main}[link={url-link-base}/ch7ex10]
image:{url-workflows}/Exercise 7.11/{url-badge-main}[link={url-link-base}/ch7ex11]
image:{url-workflows}/Exercise 7.12/{url-badge-main}[link={url-link-base}/ch7ex12]
image:{url-workflows}/Exercise 7.13/{url-badge-main}[link={url-link-base}/ch7ex13]
image:{url-workflows}/Exercise 7.14/{url-badge-main}[link={url-link-base}/ch7ex14]
image:{url-workflows}/Exercise 7.15/{url-badge-main}[link={url-link-base}/ch7ex15]
