= Exercise 5.10
// Refs:
:url-base: https://github.com/fenegroni/TGPL-exercise-solutions
:workflow: workflows/Exercise 5.10
:action: actions/workflows/ch5ex10.yml
:url-workflow: {url-base}/{workflow}
:url-action: {url-base}/{action}
:badge-exercise: image:{url-workflow}/badge.svg?branch=main[link={url-action}]

{badge-exercise}

Rewrite `topoSort` to use maps instead of slices and
eliminate the initial sort.
Verify that the results, though nondeterministic,
are valid topological orderings.

== Test

I keep the original implementation
and rename it `originalTopoSort`.

In pure TDD style
we test the original implementation
to make sure we do have a way to verify
the result is a valid topological ordering.

Then we test the new `topoSort` implementation.

The new functions uses maps in place of slices
as explained in the book
at the end of Section 4.3
where they introduce the type graph.

== How to verify topological ordering

My idea is to validate that
there are no values appearing before their keys.

For example, given the data from the book,
in the resulting list I should not see
_algorithms_ before _data structures_.

`TestVerifyTopoSort` only tests directed acyclic graphs.

The test fails if `topoSort` fails to order
all the elements of the graph or lists elements that were not
in the original graph.
