= Exercise 5.13
// Refs:
:url-base: https://github.com/fenegroni/TGPL-exercise-solutions
:url-workflows: {url-base}/workflows
:url-actions: {url-base}/actions
:badge-exercise: image:{url-workflows}/Exercise 5.13/badge.svg?branch=main[link={url-actions}]

{badge-exercise}

Modify `crawl` to make local copies of the pages it finds,
creating directories as necessary.
Don't make copies of pages that come from a different domain.
For example, if the original page comes from `golang.org`,
save all files from there,
but exclude ones from `vimeo.com`.

== Test

We will use package `net/httptest` to set up
an in place server and provide the
package `links` under test with the HTTP client.

One test to check files are saved as returned by the server.

Another test to make sure the server is not called for
resources from domains other than `golang.org`.

We use Afero to access a virtualised file system.
Initially we are allowing the code to work as before,
accessing files that we need to validate.

A possible improvement is to instead mock the filesystem
and check that files are written with the expected content,
without having to read them back in the test
to validate them.
