= Chapter 5
// Refs:
:url-base: https://github.com/fenegroni/TGPL-exercise-solutions
:url-workflows: {url-base}/workflows
:url-actions: {url-base}/actions
:badge-chapter5: image:{url-workflows}/Chapter 5/badge.svg?branch=main[link={url-actions}]
:badge-exercise51: image:{url-workflows}/Exercise 5.1/badge.svg?branch=main[link={url-actions}]
:badge-exercise52: image:{url-workflows}/Exercise 5.2/badge.svg?branch=main[link={url-actions}]
:badge-exercise53: image:{url-workflows}/Exercise 5.3/badge.svg?branch=main[link={url-actions}]
:badge-exercise54: image:{url-workflows}/Exercise 5.4/badge.svg?branch=main[link={url-actions}]

{badge-chapter5}

== Functions

* {url-base}/tree/master/chapter5/exercise5.1[Exercise 5.1] {badge-exercise51} +
Change the `findlinks` program to traverse the `n.FirstChild` linked list
using recursive calls to `Visit` instead of a loop.
* {url-base}/tree/master/chapter5/exercise5.2[Exercise 5.2] {badge-exercise52} +
Write a function to populate a mapping from element names - `p`, `div`, `span` and so on -
to the number of elements with that name in an HTML document tree
* {url-base}/tree/master/chapter5/exercise5.3[Exercise 5.3] {badge-exercise53} +
Write a function to print the contents of all text nodes in an HTML document tree.
Do not descend into <script> or <style> elements,
since their content are not visible in a web browser.
* {url-base}/tree/master/chapter5/exercise5.4[Exercise 5.4] {badge-exercise54} +
Extend the `Visit` function so that
it extracts other kinds of links from the document,
such as images, scripts, and style sheets.
