= Chapter 5
// Refs:
:url-base: https://github.com/fenegroni/TGPL-exercise-solutions
:url-workflows: {url-base}/workflows
:url-actions: {url-base}/actions
:badge-chapter5: image:{url-workflows}/Chapter 5/badge.svg?branch=main[link={url-actions}]
:badge-exercise5-1: image:{url-workflows}/Exercise 5.1/badge.svg?branch=main[link={url-actions}]
:badge-exercise5-2: image:{url-workflows}/Exercise 5.2/badge.svg?branch=main[link={url-actions}]
:badge-exercise5-3: image:{url-workflows}/Exercise 5.3/badge.svg?branch=main[link={url-actions}]
:badge-exercise5-4: image:{url-workflows}/Exercise 5.4/badge.svg?branch=main[link={url-actions}]
:badge-exercise5-5: image:{url-workflows}/Exercise 5.5/badge.svg?branch=main[link={url-actions}]
:badge-exercise5-6: image:{url-workflows}/Exercise 5.6/badge.svg?branch=main[link={url-actions}]

{badge-chapter5}

== Functions

* {url-base}/tree/master/chapter5/exercise5.1[Exercise 5.1] {badge-exercise5-1} +
Change the `findlinks` program to traverse the `n.FirstChild` linked list
using recursive calls to `Visit` instead of a loop.
* {url-base}/tree/master/chapter5/exercise5.2[Exercise 5.2] {badge-exercise5-2} +
Write a function to populate a mapping from element names - `p`, `div`, `span` and so on -
to the number of elements with that name in an HTML document tree
* {url-base}/tree/master/chapter5/exercise5.3[Exercise 5.3] {badge-exercise5-3} +
Write a function to print the contents of all text nodes in an HTML document tree.
Do not descend into <script> or <style> elements,
since their content are not visible in a web browser.
* {url-base}/tree/master/chapter5/exercise5.4[Exercise 5.4] {badge-exercise5-4} +
Extend the `Visit` function so that
it extracts other kinds of links from the document,
such as images, scripts, and style sheets.
* {url-base}/tree/master/chapter5/exercise5.5[Exercise 5.5] {badge-exercise5-5} +
Implement `countWordsAndImages`.
* {url-base}/tree/master/chapter5/exercise5.6[Exercise 5.6] {badge-exercise5-6} +
Modify the `corner` function in section 3.2 of the book,
to use named results and a bare return statement.
