= Exercise 5.7
// Refs:
:url-base: https://github.com/fenegroni/TGPL-exercise-solutions
:url-workflows: {url-base}/workflows
:url-actions: {url-base}/actions
:badge-exercise: image:{url-workflows}/Exercise 5.7/badge.svg?branch=main[link={url-actions}]

{badge-exercise}

Develop `startElement` and `endElement` into a general HTML pretty-printer.
Print comment nodes, `text` nodes, and attributes of each element (`<a href='...'>`).
Use short forms like `<img/>` instead of `<img></img>` when an element has no children.
Write a test to ensure the output can be parsed successfully. (See Chapter 11.)

== Test

We test the implementation of `PrettyPrint`,
which reads from `input`, writes to `output`,
and performs the task in our exercise.

The implementation is a little flaky:

. it uses global variables to keep track of state.

. `startElement` prints the start tag of an HTML element
by relying on being called the first time an element is encountered,
before all child elements are visited.

. `endElement` prints the end tag of the element
by relying on being called after all child nodes are visited.

. indenting the output requires a global `depth`,
incremented by `startElement` and decremented by `endElement`.
