= Exercise 5.9
// Refs:
:url-base: https://github.com/fenegroni/TGPL-exercise-solutions
:workflow: workflows/Exercise 5.9
:action: actions/workflows/ch5ex9.yml
:url-workflow: {url-base}/{workflow}
:url-action: {url-base}/{action}
:badge-exercise: image:{url-workflow}/badge.svg?branch=main[link={url-action}]

{badge-exercise}

Write a function `expand(s string, f func(string) string) string`
that replaces each substring "```$foo```" within `s`
by the text returned by `f("foo")`.

== Test

We validate substitutions work like they do in `bash`
when the `$` variable notation is used
without a pair of `{` and `}`.

The test cases cover
empty identifiers,
unicode characters,
consecutive identifiers,
empty strings.

== Implementation

We only substitute identifiers that are made of letters and not numbers.

We match everything between `$` and the next non-letter rune.

For example, if the function `f` returns `123` for `number`, given:

====
This is a $number.
====

the replaced string will be:

====
This is a 123.
====

But given this string:

====
These are $numbers.
====

the replacement will be:

====
These are
====

That is, we don't do partial matching.

== Identifiers

We define a function, `notIdentifierRune`,
to determine what runes are recognised
as characters of an identifier.
