= Exercise 7.9
// Refs:
:url-base: https://github.com/fenegroni/TGPL-exercise-solutions
:url-workflows: {url-base}/workflows
:url-actions: {url-base}/actions
:badge-exercise: image:{url-workflows}/Exercise 7.9/badge.svg?branch=main[link={url-actions}]

{badge-exercise}

Use the `html/template` package (Section 4.6) to replace `printTracks` with a function
that displays the tracks as an HTML table. Use the solution to the previous exercise to arrange
that each click on a column head makes an HTTP request to sort the table.

== Test

The exercise requires us to implement the
integration of two separate pieces of functionality:

. the HTML output in table form with hyperlinks in the headers
. the ordering of the table contents to use the ordering from exercise 7.8

The integration of those two separate requirements requires us to implement
a web routine that responds to the hyperlink to decide how to further order the data.

== Strategy

My TDD strategy for this exercise is to validate the integration of all
the different bits first. The test will be robust enough to give me
an idea of what the integration shoud look like.

I will further refine the test as I implement the different parts,
by implementing more detailed tests for the parts that need more robust validation.

The decision to not implement what most people would call Unit Tests
is intenional: rather than focusing on the detail of the implementation
which might change, I am focusing on the end result first
and use those aspects of the solution to guide me further.

== Front end

I am not a front end web developer.

I expect the HTML output to be the bare minimum that satisfies the requirements:
a basic table with no borders and headers that contain fixed hyperlinks.

== Integration

The integration test will extract elements from the table
by id so that we know the order is correct
and will then extract the URL from a known element
to then make an HTTP call and get the next result.

== Leverage exercise 5.8

In exercise 5.8 we wrote a function `ElementByID`
to extract the correct elements by ID.

This will be the first part of the integration test:
given the HTML output
extract the elements of the table
and the links from the headers.

== Advantage of TDD approach

Because we know from the very beginning that we must somehow test our solution,
nd because we are starting from an integration test,
our output will be a lot better quality, and our tests less brittle.

Not only HTML elements will have an ID, but their IDs will be generated
so that we can pick individual items and validate their position,
order, attributes, etc.

This attitude towards generating output this way is not so much about
saving effort later, but instead it esnures refactoring is less risky.

== Http Handler

We leverage what we learnt in exercise 5.6 to write a handler